import { CONFIG } from "../config.js";
import { APP_STATE } from "../utils/state.js";
import { openActionModal } from "../utils/modal.js";
import { sendTransaction } from "./radix.js";

function instantiateManifest({ maxPerTx, multisig, dailyCap, agentName, notarizerAccount }) {
  const account = APP_STATE.activeAccount.address;
  const assets = CONFIG.ALLOWED_ASSETS.map(a =>
    `Tuple("${a.name}", Address("${a.address}"))`
  ).join(", ");

  return `
CALL_FUNCTION
    Address("${CONFIG.PACKAGE_ADDRESS}")
    "PolicyVault"
    "instantiate"
    Decimal("${maxPerTx}")
    Decimal("${multisig}")
    Decimal("${dailyCap}")
    Array<Tuple>(Tuple("owner", Address("${account}")))
    "${agentName}"
    Address("${CONFIG.DAPP_DEFINITION}")
    Address("${CONFIG.DEV_FEE_COLLECTOR}")
    Array<Tuple>(${assets})
    Address("${notarizerAccount}")
;
CALL_METHOD
    Address("${account}")
    "deposit_batch"
    Expression("ENTIRE_WORKTOP")
;
`;
}

export async function instantiate() {
  if (!APP_STATE.activeAccount) {
    console.error("No active account");
    return;
  }

  openActionModal({
    title: "Instantiate Agent Wallet",
    content: `
      <div style="display:flex;flex-direction:column;gap:16px;margin-top:8px;">
        <div>
          <label style="font-size:13px;color:#8b949e;">Agent Name</label>
          <p style="font-size:12px;color:#555;margin:2px 0 6px;">A name to identify your agent.</p>
          <input id="inst-name" type="text" placeholder="my-trading-agent"
            style="width:100%;padding:8px;border-radius:8px;background:#111;color:white;border:1px solid #333;box-sizing:border-box;"/>
        </div>
        <div>
          <label style="font-size:13px;color:#8b949e;">Notarizer Account</label>
          <p style="font-size:12px;color:#555;margin:2px 0 6px;">The agent notarizer account address generated by the SDK (agentwallet init).</p>
          <input id="inst-notarizer" type="text" placeholder="account_tdx_2_..."
            style="width:100%;padding:8px;border-radius:8px;background:#111;color:white;border:1px solid #333;box-sizing:border-box;"/>
        </div>
        <div>
          <label style="font-size:13px;color:#8b949e;">Max per Transaction</label>
          <p style="font-size:12px;color:#555;margin:2px 0 6px;">Maximum amount the agent can spend in a single transaction.</p>
          <input id="inst-max-tx" type="number" placeholder="400" min="0" step="1"
            style="width:100%;padding:8px;border-radius:8px;background:#111;color:white;border:1px solid #333;box-sizing:border-box;"/>
        </div>
        <div>
          <label style="font-size:13px;color:#8b949e;">Multisig Threshold</label>
          <p style="font-size:12px;color:#555;margin:2px 0 6px;">Maximum the agent and owner can spend together in one TX.</p>
          <input id="inst-multisig" type="number" placeholder="1000" min="0" step="1"
            style="width:100%;padding:8px;border-radius:8px;background:#111;color:white;border:1px solid #333;box-sizing:border-box;"/>
        </div>
        <div>
          <label style="font-size:13px;color:#8b949e;">Daily Cap</label>
          <p style="font-size:12px;color:#555;margin:2px 0 6px;">Maximum total spending allowed per day.</p>
          <input id="inst-daily" type="number" placeholder="10000" min="0" step="1"
            style="width:100%;padding:8px;border-radius:8px;background:#111;color:white;border:1px solid #333;box-sizing:border-box;"/>
        </div>
      </div>
    `,
    confirmText: "Instantiate",
    onConfirm: async () => {
      const agentName       = document.getElementById("inst-name").value.trim();
      const notarizerAccount = document.getElementById("inst-notarizer").value.trim();
      const maxPerTx        = document.getElementById("inst-max-tx").value.trim();
      const multisig        = document.getElementById("inst-multisig").value.trim();
      const dailyCap        = document.getElementById("inst-daily").value.trim();

      if (!agentName || !notarizerAccount || !maxPerTx || !multisig || !dailyCap) {
        console.error("All fields required for instantiate");
        return;
      }

      if (parseFloat(maxPerTx) > parseFloat(multisig)) {
        console.error("Max per TX cannot exceed Multisig Threshold");
        return;
      }

      if (parseFloat(multisig) > parseFloat(dailyCap)) {
        console.error("Multisig Threshold cannot exceed Daily Cap");
        return;
      }

      const manifest = instantiateManifest({
        maxPerTx, multisig, dailyCap, agentName, notarizerAccount
      });
      console.log("INSTANTIATE MANIFEST:", manifest);
      await sendTransaction(manifest);
    }
  });
}
